/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GameRouteImport } from './routes/game'
import { Route as FlappyClassicRouteImport } from './routes/flappy-classic'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSecretsRouteImport } from './routes/admin.secrets'
import { Route as AdminLevelIdRouteImport } from './routes/admin.level.$id'
import { Route as AdminDepositsStatusRouteImport } from './routes/admin.deposits.$status'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const FlappyClassicRoute = FlappyClassicRouteImport.update({
  id: '/flappy-classic',
  path: '/flappy-classic',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecretsRoute = AdminSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLevelIdRoute = AdminLevelIdRouteImport.update({
  id: '/level/$id',
  path: '/level/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsStatusRoute = AdminDepositsStatusRouteImport.update({
  id: '/deposits/$status',
  path: '/deposits/$status',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dev': typeof DevRoute
  '/flappy-classic': typeof FlappyClassicRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/trial': typeof TrialRoute
  '/wallet': typeof WalletRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/deposits/$status': typeof AdminDepositsStatusRoute
  '/admin/level/$id': typeof AdminLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dev': typeof DevRoute
  '/flappy-classic': typeof FlappyClassicRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/trial': typeof TrialRoute
  '/wallet': typeof WalletRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/deposits/$status': typeof AdminDepositsStatusRoute
  '/admin/level/$id': typeof AdminLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dev': typeof DevRoute
  '/flappy-classic': typeof FlappyClassicRoute
  '/game': typeof GameRoute
  '/leaderboard': typeof LeaderboardRoute
  '/trial': typeof TrialRoute
  '/wallet': typeof WalletRoute
  '/admin/secrets': typeof AdminSecretsRoute
  '/admin/deposits/$status': typeof AdminDepositsStatusRoute
  '/admin/level/$id': typeof AdminLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dev'
    | '/flappy-classic'
    | '/game'
    | '/leaderboard'
    | '/trial'
    | '/wallet'
    | '/admin/secrets'
    | '/admin/deposits/$status'
    | '/admin/level/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dev'
    | '/flappy-classic'
    | '/game'
    | '/leaderboard'
    | '/trial'
    | '/wallet'
    | '/admin/secrets'
    | '/admin/deposits/$status'
    | '/admin/level/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dev'
    | '/flappy-classic'
    | '/game'
    | '/leaderboard'
    | '/trial'
    | '/wallet'
    | '/admin/secrets'
    | '/admin/deposits/$status'
    | '/admin/level/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DevRoute: typeof DevRoute
  FlappyClassicRoute: typeof FlappyClassicRoute
  GameRoute: typeof GameRoute
  LeaderboardRoute: typeof LeaderboardRoute
  TrialRoute: typeof TrialRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flappy-classic': {
      id: '/flappy-classic'
      path: '/flappy-classic'
      fullPath: '/flappy-classic'
      preLoaderRoute: typeof FlappyClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/secrets': {
      id: '/admin/secrets'
      path: '/secrets'
      fullPath: '/admin/secrets'
      preLoaderRoute: typeof AdminSecretsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/level/$id': {
      id: '/admin/level/$id'
      path: '/level/$id'
      fullPath: '/admin/level/$id'
      preLoaderRoute: typeof AdminLevelIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits/$status': {
      id: '/admin/deposits/$status'
      path: '/deposits/$status'
      fullPath: '/admin/deposits/$status'
      preLoaderRoute: typeof AdminDepositsStatusRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSecretsRoute: typeof AdminSecretsRoute
  AdminDepositsStatusRoute: typeof AdminDepositsStatusRoute
  AdminLevelIdRoute: typeof AdminLevelIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSecretsRoute: AdminSecretsRoute,
  AdminDepositsStatusRoute: AdminDepositsStatusRoute,
  AdminLevelIdRoute: AdminLevelIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DevRoute: DevRoute,
  FlappyClassicRoute: FlappyClassicRoute,
  GameRoute: GameRoute,
  LeaderboardRoute: LeaderboardRoute,
  TrialRoute: TrialRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
